### ISSUE TITLE
Seeing double counters when using evil-anzu

### ISSUE THREAD

**Issue by dieggsy** [TheBB/spaceline#130]
<img width="318" alt="screen shot 2017-02-07 at 10 56 12" src="https://cloud.githubusercontent.com/assets/9020453/22699029/3d1de5de-ed24-11e6-9369-724717281073.png">

Additionally, `spaceline-toggle-anzu` turns off the one of the right, but not the one on the left.

**Comment by TheBB** [comment]
You need to disable anzus own modeline capabilities. I'm pretty sure I documented this in the readme.

**Comment by therockmandolinist** [comment]
The readme says to initialize spaceline after anzu, which I'm doing. Is there a more explicit way to disable anzu's modeline capabilities?

It may or may not be relevant that I am using [evil-anzu](https://github.com/syohex/emacs-evil-anzu) and not [anzu](https://github.com/syohex/emacs-anzu)

**Comment by spegoraro** [comment]
I'm experiencing the same using regular anzu. It is being loaded before spaceline but still getting double output. 

The solution as @TheBB has touched on is to disable anzu's own modeline with `(setq anzu-cons-mode-line-p nil)`. 

I think it would be a good idea to add this to the README instead of just saying to load anzu first.
