### ISSUE TITLE
Spaceline counts columns from 0

### ISSUE THREAD

**Issue by ghost** [TheBB/spaceline#138]
Vim counts columns from 1.

Since Spacemacs emulates Vim, perhaps edit Spaceline (the status line) to display the column as "current-column + 1". That way we get sane character counting in Spacemacs too.

This is how badly it "works" at the moment:

1st character of 1st line:

- Vim: 1:1
- Spacemacs: 1:0

80th character of 1st line:

- Vim: 1:80
- Spacemacs: 1:79

Very confusing. I noticed that it's because Emacs itself defines "current-column" as 0-indexed. But that's not user friendly. Why does Emacs even bother counting lines starting from 1 when it insanely counts characters starting from 0? They should have made both 0 or both 1. This mishmash is a mess.

Most annoyingly, it means that stuff like fill-column and git commit message editing gets confusing. "50" is actually the 51st column, etc. No other sane editor counts columns the bad way Emacs does it...

---

In fact, even Emacs itself is being schizophrenic about this problem, because things like its built-in "fill-column" property are defined as 1-indexed values, so "fill-column 80" means "wrap all text at the real 80th column", aka "current-column 79". Heh.

Example of fill-column 80 (so column 81 and up are marked in red):

![fill80](https://cloud.githubusercontent.com/assets/22373193/24171784/16b9dac8-0e86-11e7-8d27-2c9bcc1dfd11.png)

My cursor is placed on the (non-red) 80th column... and Spacemacs shows... 1:79 as the line location.

So really, Emacs made some neurotic, bad choice for `current-column` column-counting back in its early days, and that zero-indexing makes no sense at all: 1. Compared to Vim and any other sane editor. 2. Compared to ITS OWN built-in functions.

Luckily this should be a simple fix. Just use "current-column + 1" in Spaceline instead.

I would submit a pull request but I couldn't find the code location, so someone familiar with Powerline and Spaceline will have to look at it.

---

Note: This is an issue moved from https://github.com/syl20bnr/spacemacs/issues/8550 to here instead.

**Comment by jupl** [comment]
I'm assuming it's [here](https://github.com/TheBB/spaceline/blob/master/spaceline-segments.el#L168)? If anything perhaps create a variable to adjust the offset? That way people can choose what do people prefer.

**Comment by SteveJobzniak** [comment]
@jupl It's been a while but I think I already tried editing that line and it didn't work. Which is why I opened this ticket.

I can see the place where the column view is defined, at least:

https://github.com/TheBB/spaceline/blob/master/spaceline-segments.el#L154

```emacs-lisp
(spaceline-define-segment line-column
  "The current line and column numbers, or `(current page/number of pages)`
in pdf-view mode (enabled by the `pdf-tools' package)."
  (if (eq 'pdf-view-mode major-mode)
      (spaceline--pdfview-page-number)
    "%l:%2c"))
```

But I cannot find where it's being called.

**Comment by TheBB** [comment]
The `%c` code is for column number. `spaceline--column-number-at-pos` is used for the selection size only. If you like you can rewrite the column and line-column segments to use that function instead.

The reason for this is that in Emacs, by convention, the cursor is always considered to be between two characters, rather than *on* a character. Vimmers usually take the other approach. Indeed it seems other editors of the between-mold (most of them) tend to display the index of the character on the right rather than the one on the left.

Since Spaceline (and Spacemacs for that matter) servers pure Emacs users, too, I don't want to make such a change global and irreversible, at the very least.

**Comment by SteveJobzniak** [comment]
@TheBB Do you mean that "%c" is a special macro string which Emacs expands to "column"? What's causing that expansion?

The best solution would be a `spaceline-column-zeroindex nil` property to toggle 1-indexing. Any takers?

**Comment by TheBB** [comment]
https://www.gnu.org/software/emacs/manual/html_node/elisp/Mode-Line-Format.html

https://www.gnu.org/software/emacs/manual/html_node/elisp/_0025_002dConstructs.html#g_t_0025_002dConstructs

**Comment by SteveJobzniak** [comment]
@TheBB Ohh thanks for the explanation, that explains why I didn't find the column code earlier. It was just a text macro!

Hmm, well, something like this then (I've forgotten emacs-lisp, so this is pseudocode):

```emacs-lisp
(spaceline-define-segment line-column
  "The current line and column numbers, or `(current page/number of pages)`
in pdf-view mode (enabled by the `pdf-tools' package)."
  (if (eq 'pdf-view-mode major-mode)
      (spaceline--pdfview-page-number)
    (if (eq 'spaceline-column-zeroindex t)
        "%l:%2c"
      (--other code to return column+1))))
```
