### ISSUE TITLE
error message at startup

### ISSUE THREAD

**Issue by vakosel** [TheBB/spaceline#63]
Before everything well done for your efforts. 
Ex-vim (not sure about that  :-) yet) and a wanna be emacs user thanks to Evil.
I watched your video on spacemacs and really liked it. So i decided it to play with the configuration.

Everything works fine ( i use your dot file  , space-layers and spaceline) but  i get this error ( single one !) on startup 

 Error in dotspacemacs/user-config: Wrong number of arguments: (lambda (mode unicode &optional ascii) "Diminish MODE name in mode line to UNICODE or ASCII depending on the value
`dotspacemacs-mode-line-unicode-symbols'.
If ASCII si not provided then UNICODE is used instead." (list (quote add-to-list) (quote (quote spacemacs--diminished-minor-modes)) (list (quote quote) (list mode unicode ascii)))), 1

Any idea ?  
Thanks in advance

PS. My dot file is exactly like yours except some programming languages that i am not interested in , reproduced both in terminal (urxvt) and on gui mode.
ArchLinux Os.

**Comment by TheBB** [comment]
Is it perhaps because you are running the master version of Spacemacs? (The release version.)

I run Spacemacs develop so my config reflects that. I don't really aim to support it for others, so I can't really recommend to use it as-is for yourself, whether develop or not.

I'm guessing that the likeliest fix is that the calls to `spacemacs|diminish` at line 403 and 404 are broken on master since the second argument to `spacemacs|diminish` was made optional in develop. Therefore you can try `(spacemacs|diminish hybrid-mode nil)` and accordingly for `which-key-mode`.

In the future you can ask at https://github.com/TheBB/spacemacs-layers, since this isn't really a Spaceline problem.

**Comment by vakosel** [comment]
thansk a lot ! 
that was it..
