### ISSUE TITLE
Changing the font color of powerline-active2 face

### ISSUE THREAD

**Issue by emacsuser123** [TheBB/spaceline#89]
Hi.

I'm having a problem when using the spaceline modeline. The font color of the different segments using powerline-active2 face is black, and the background color used on this face is dark grey (or dark blue, in others),which makes very difficult to read its content.

How can I change either the font color or the background color on a specific face?

As per the README file, I assume that, after highlight face, the remaining segments are given the face powerline-active1 and powerline-active2 alternatively, with the central segment being modeline.
The ones that are giving problems to me are the 3rd,5th, ... from left to right, and same numbers from right to left, which should have powerline-active2 as per the README file.
 
Thanks.
-Bob

**Comment by gmoutso** [comment]
A quick solution would be 
(set-face-foreground 'powerline-active2 "white")
My problem was solved by setting powerline-active1. An example of setting spaceline-face-func can be found on [stackexchange](http://emacs.stackexchange.com/a/22655).

I also did not understand which faces are used by setting face1, face2, line and highlight and why the default did not work nicely for me. The relevant part from spaceline.el is:
`(defun spaceline--get-face (face active)
  "Universal function to get the right face.
FACE and ACTIVE have the same meanings as in
`spaceline-face-func'.  It delegates the work to
`spaceline-face-func' if it is given, otherwise falls back to
default configuration."
  (if spaceline-face-func
      (funcall spaceline-face-func face active)
    (cond
     ((eq 'face1 face) (if active 'powerline-active1 'powerline-inactive1))
     ((eq 'face2 face) (if active 'mode-line 'mode-line-inactive))
     ((eq 'line face) (if active 'powerline-active2 'powerline-inactive2))
     ((eq 'highlight face) (if active
                               (funcall spaceline-highlight-face-func)
                             'powerline-inactive1)))))
`

**Comment by emacsuser123** [comment]
@gmoutso:
Thanks a lot.
Your answer helped me a lot.
In fact, in the end, it was powerline-active1, and not powerline-active2, the one that solved my problem. I do not understand why, since there is a segment to the left of this one, and hence powerline-active2 should be the one, but anyway, using your statement it worked perfectly well.

I had solved it using a much more arcane approach, that turned all the fonts in my modeline to white, and not only the ones corresponding to dark segments. I used the following in the custom faces section:
 '(mode-line ((t (:background "grey75" :foreground "white" :box (:line-width -1 :style released-button)))))

But, clearly, I prefer your solution.

Thanks a lot.
-Bob
